### ISSUE TITLE
Is there any plan for React Version ?

### ISSUE THREAD

**Issue by collegeimprovements** [epicmaxco/epic-spinners#1]

**Comment by smartapant** [comment]
@collegeimprovements we're not sure right now about react (and angular) versions. In the meantime, we provide html/css snippets you can grab from our demo website and use with any framework :)

**Comment by mehrdad-shokri** [comment]
@smartapant I can open a pr and help develop the react version. interested in discussion?

**Comment by xRahul** [comment]
I can help creating the react components.

**Comment by smartapant** [comment]
@mehrdaad @xRahul would be interesting :)

**Comment by mehrdad-shokri** [comment]
@smartapant alright, how we're gonna handle it? Should we create another repo? or do it as a mono repo?

**Comment by smartapant** [comment]
@mehrdaad @xRahul I think separate repo is nice, check out https://github.com/hackafro/angular-epic-spinners

**Comment by bondz** [comment]
@smartapant I recreated the components using React see https://github.com/bondz/react-epic-spinners

**Comment by smartapant** [comment]
@bondz nice! will list your repo in our Readme :)
