### ISSUE TITLE
Set colour through CSS

### ISSUE THREAD

**Issue by callumthomson** [epicmaxco/epic-spinners#14]
Hello,

I like this package a lot, but I cannot figure out a way to set the colour of the spinners using only css. It seems it can only be done by passing a colour value as a prop? I have global site colours set in a scss variables file and I want to be able use those variables to set the colour of the spinners. At the moment I just have to copy the colours from my variables file which is far from ideal.

Is there a solution?

Thanks

**Comment by smartapant** [comment]
Hi @callumthomson !

Unfortunately, js way :(

You can create palette-config inside vuex to use the colors inside javascript
