### ISSUE TITLE
Compatibility with newest Vue version or Nuxt

### ISSUE THREAD

**Issue by mzastue** [epicmaxco/epic-spinners#20]
Hi, it looks like its not working with newest Vue version (2.5.17). In package.json there is a fixed version (2.5.16).

To replicate I used Nuxt v1.0 for example with adding this package. Until you will use vue version from nuxt (always the newest one) there will be this bug.

Thanks! Good work anyway!

**Comment by smartapant** [comment]
Hi @mzastue !

Thanks for reporting) We'll try to find some time to fix that thing :D

**Comment by smartapant** [comment]
@mzastue haven't checked yet, but must be fixed in 1.0.4 version

**Comment by mzastue** [comment]
Hi @smartapant, cool - no worries ;D

Looks like it's fine just to remove fixed version from package.json

**Comment by smartapant** [comment]
@mzastue nice :)
