### ISSUE TITLE
FulfillingBouncingCircleSpinner - Bootstrap shadow-lg

### ISSUE THREAD

**Issue by Kyriakos-Michael** [epicmaxco/epic-spinners#22]
FulfillingBouncingCircleSpinner - Bootstrap shadow-lg

When adding on the Class shadow-lg from Bootstrap, the square background is showing. 
NOTE: The background panel of the spinner to be a blue like color so you can see it.

Let me know for help to reproduce. 

KyriakosMichael.

Example:
```

<FulfillingBouncingCircleSpinner
 slot="board-item-slot"
 class="offset-6 shadow-lg" 
      :size="50"
      color="grey"
     v-if="isLoading"
 />
```

**Comment by asvae** [comment]
Tried on a couple of spinners. That seems to be a correct behavior to me.

![image](https://user-images.githubusercontent.com/5394573/56358796-68332500-61e8-11e9-87cb-5418434cea22.png)
