### ISSUE TITLE
"SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"

### ISSUE THREAD

**Issue by BenAHammond** [epicmaxco/epic-spinners#24]
The "SpringSpinner" appears to be trying, and failing, to access a stylesheet on the document and the result are ugly JS errors on load.

The offending code seems to be inside of the SpringSpinner:

```
appendKeyframes: function (name, frames) {
    var idx = document.styleSheets[0].cssRules.length
    document.styleSheets[0].insertRule('@keyframes ' + name + ' { ' + frames + ' }', idx)
  }
```
```
vue.runtime.esm.js?2b0e:601 [Vue warn]: Error in mounted hook: "SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"

found in

---> <SpringSpinner> at node_modules/epic-spinners/src/components/lib/SpringSpinner.vue
```

**Comment by seb-vial** [comment]
Same issue here

**Comment by ciryon** [comment]
Also here. I had a working component with an epic spinner than suddenly once I started working on some new features in the component, unrelated to the spinner, and this error pops up.
