### ISSUE TITLE
Importing a single spinner adds the entire collection of spinners to prod build

### ISSUE THREAD

**Issue by chriszrc** [epicmaxco/epic-spinners#25]
If I include a single spinner in my vue cli 3 project:

```
import bButton from 'bootstrap-vue/es/components/button/button';

import { HalfCircleSpinner } from 'epic-spinners';

@Component({
  components:{
    bButton,
    HalfCircleSpinner,
  },
})
//etc
```

This is what I see in the source-map explorer after executing a build:prod

<img width="1155" alt="screen shot 2019-01-08 at 9 56 44 am" src="https://user-images.githubusercontent.com/25695785/50838320-c324c880-132b-11e9-9508-adc9d5fdd3eb.png">

I would have expected that given I'm only including a single component, and that component doesn't depend on the other spinners, that I'd be able to import it singly?

**Comment by RDelorier** [comment]
I'm getting the same result on an inherited project, it uses just 1 spinner and is the largest dependency.

![screen shot 2019-01-24 at 4 11 52 am](https://user-images.githubusercontent.com/2295675/51667506-4bdb6f80-1f8e-11e9-9d88-a7768b4cda64.png)

**Comment by RDelorier** [comment]
nvm I just imported the component directly and it fixed it
```js
// before 
import {PixelSpinner} from 'epic-spinners'

// after
import PixelSpinner from 'epic-spinners/src/components/lib/PixelSpinner'
```

![screen shot 2019-01-24 at 4 17 25 am](https://user-images.githubusercontent.com/2295675/51667894-f94e8300-1f8e-11e9-9f05-5087499fff02.png)

**Comment by chriszrc** [comment]
@RDelorier yay! confirmed, I see it working here on my project as well-

**Comment by asvae** [comment]
Importing file is the only way to get correct tree-shaking from current build.

Added the instruction to the docs.

We also plan more fundamental solution for the problem and it's moved to #32
