### ISSUE TITLE
Setting defaults for spinners

### ISSUE THREAD

**Issue by mubaidr** [epicmaxco/epic-spinners#28]
Is there any to set custom default (timing, color etc) so that it would just work with `<atom-spinner/>`

**Comment by asvae** [comment]
Do you want a global default?

So far we provide component default and a way to override via props.

**Comment by asvae** [comment]
The simplest solution I can think of is to use [`extends`](https://vuejs.org/v2/api/#extends) and override the props as you see fit.

Providing an API in no hacky way would involve doing vue plugin. And that's kinda a lot of boilerplate for users.
