### ISSUE TITLE
Any plan to have them overlay a container?

### ISSUE THREAD

**Issue by jess8bit** [epicmaxco/epic-spinners#3]
Very nice spinnerzzz! :thumbsup:

I wonder, do you plan to add an optional property (or another mechanism) on the vue component, in order  to make a spinner overlay its container that would then appear underneath (z-index, opacity) while the spinner runs? So to prevent a user action in that covered region meanwhile.

**Comment by smartapant** [comment]
Hey @jess8bit 

Thanks for appreciation!

Right now you can create a wrapper for that. I will keep this issue open in case there will be many requests for this feat.

Have a good day!
