### ISSUE TITLE
Register globally?

### ISSUE THREAD

**Issue by ghost** [epicmaxco/epic-spinners#36]
Hi!

I tried registering it globally, but to no avail.

What I tried was:
import { HollowDotsSpinner } from 'epic-spinners'

Vue.component('hollow-dots-spinner', {
  components: {
    HollowDotsSpinner
  }
})
Vue.use(hollow-dots-spinner)

Also tried passing it as a value in new vue as well as components but to no avail. Didn't find anything about this in the docs, or did I miss something completely?

Thanks for any inputs here.

**Comment by trlehmbecker** [comment]
I was able to register it like so

```javascript
import { HollowDotsSpinner } from 'epic-spinners'
Vue.component('hollow-dots-spinner', HollowDotsSpinner);
```
