### ISSUE TITLE
epic-spinners.min.css - ParseError: Unexpected token 

### ISSUE THREAD

**Issue by zach-data** [epicmaxco/epic-spinners#4]
I'm having issues when trying to add this collection into an existing project using browserify. 

```
$ npm run build
> cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/build.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/build.js

/sitedir/node_modules/epic-spinners/dist/lib/epic-spinners.min.css:1
.hollow-dots-spinner[data-v-28280fa3],.hollow-dots-spinner ... 
^
ParseError: Unexpected token
```

Any guidance?

**Comment by jean-moldovan** [comment]
Hm, seems to be related to:
* https://github.com/nguyenvanduocit/vue-loading-spinner/issues/11
* https://github.com/vuejs/vueify/issues/108

Was able to reproduce using `vue-cli browserify` template.

Didn't do much research, but looks like we might need to fiddle with browserify config (transform = babelify + vueify) to see if there is a workaround.

If there is, maybe `vue-cli browserify` could take care of this out of the box.

Thanks!
