### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by asvae** [epicmaxco/epic-spinners#41]
https://epic-spinners.epicmax.co/
![image](https://user-images.githubusercontent.com/5394573/86821324-efd9ad80-c092-11ea-9c43-739254472f65.png)
![image](https://user-images.githubusercontent.com/5394573/86821371-fb2cd900-c092-11ea-8ad4-399ce4705aa3.png)

**Comment by RVitaly1978** [comment]
This issue is related to the `epic-spinner-landing` project: https://github.com/epicmaxco/epic-spinners-landing/pull/1
