### ISSUE TITLE
Vue.js 3

### ISSUE THREAD

**Issue by sistematico** [epicmaxco/epic-spinners#46]
Anyway to use this with Vue.js 3?

**Comment by asvae** [comment]
Hey. Probably no, but we'll take a look :D.
Shouldn't be too hard to fix.

**Comment by sirwalterious** [comment]
@asvae Any update on this, or an ETA?

**Comment by flopana** [comment]
Bump

**Comment by mgd216** [comment]
Bump++

**Comment by yungParrot** [comment]
I've installed it my Vue 3 project and it seems to work... I don't remember if I had to configure anything 🤔 I think it was working out of the box. 
```vue
<template>
  <HalfCircleSpinner
    :animation-duration="1000"
    :size="30"
    color="#ffffff"
  />
</template>

<script setup lang="ts">
import { HalfCircleSpinner } from "epic-spinners"
</script>
```  
although I do get errors from yarn:
```
...
warning " > epic-spinners@1.1.0" has incorrect peer dependency "vue@^2.5.2".
...
```

🤠

**Comment by DerZwergGimli** [comment]
package.json
```  
"peerDependencies": {
    "vue": "^2.5.2"
  },
```

can we set that up to ^3.1.0 
PLEASE :laughing: 

Edit: Wasnt that easy to fix all deps but at least i can now deploy again - would appreciate  a new version like: epic-spinners3

**Comment by bhanu2217** [comment]
When are you planning to have release for Vue.JS 3?
