### ISSUE TITLE
Angular components for epic spinners

### ISSUE THREAD

**Issue by HackAfro** [epicmaxco/epic-spinners#5]
Thinking of creating angular components for epic spinners. I can create a pull request and start working on it if that's okay

**Comment by smartapant** [comment]
@HackAfro do you want to build it in the same repo with vue elements?

**Comment by HackAfro** [comment]
@smartapant I was thinking of creating a separate repo for it.

**Comment by HackAfro** [comment]
@smartapant I've successfully created angular components epic spinners. [Angular-epic-spinners](https://github.com/hackafro/angular-epic-spinners)  feedback and comments are welcome.

**Comment by smartapant** [comment]
@HackAfro wow, great!

I will add your lib to our readme.
Could you also mention us in your readme? Also, our team's proper name is 'epicmax', and on your website we're 'Epicmaxco' :)
