### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by likeadeckofcards** [epicmaxco/epic-spinners#6]
On the gallary [website](http://epic-spinners.epicmax.co/#/), there are two errors in the source code displayed for the spinners. The Fulfilling Square and Fulfilling Bouncing Circle are swapped.

**Comment by smartapant** [comment]
@infernobass7 thanks! will check that

**Comment by smartapant** [comment]
@infernobass7 could you please provide the errors? I cannot reproduce it

**Comment by likeadeckofcards** [comment]
Please see the screenshot below.

![epic-spinners](https://user-images.githubusercontent.com/6399755/35386879-99bc2328-019b-11e8-853c-e6cc6918ee49.PNG)

**Comment by smartapant** [comment]
@infernobass7 thanks, fixed
