### ISSUE TITLE
Can you add a type declaration for TypeScript ?

### ISSUE THREAD

**Issue by Sun1ive** [epicmaxco/epic-spinners#8]
Hi! Thank you for this lib. I've imported your awesome spinner in my ts file and got this error:

> 31:40 Could not find a declaration file for module 'epic-spinners'. 'F:/work/dashboard/node_modules/epic-spinners/src/lib.js' implicitly has an 'any' type.
>   Try `npm install @types/epic-spinners` if it exists or add a new declaration (.d.ts) file containing `declare module 'epic-spinners'

is there any typing for you package ?

**Comment by chriszrc** [comment]
While types are nice, you can use any regular es6 project like this by just adding the following to an arbitrarily named .d.ts file placed in your src folder:

//index.d.ts
```
declare module 'epic-spinners';
```

You won't get type completion, but for a component like this, you don't really need it. You can create a more elaborate type declaration file, see the following link-

Ref: https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2
